<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260224100818 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admin (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_880E0D76A76ED395 ON admin (user_id)');
        $this->addSql('CREATE TABLE coordinator (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_15FE0E6AA76ED395 ON coordinator (user_id)');
        $this->addSql('CREATE TABLE coordinator_school_class (coordinator_id INT NOT NULL, school_class_id INT NOT NULL, PRIMARY KEY (coordinator_id, school_class_id))');
        $this->addSql('CREATE INDEX IDX_AE45A48CE7877946 ON coordinator_school_class (coordinator_id)');
        $this->addSql('CREATE INDEX IDX_AE45A48C14463F54 ON coordinator_school_class (school_class_id)');
        $this->addSql('CREATE TABLE equipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, room_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D338D58354177093 ON equipment (room_id)');
        $this->addSql('CREATE TABLE room (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, capacity INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE school_class (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE student (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, class_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B723AF33EA000B10 ON student (class_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B723AF33A76ED395 ON student (user_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, coordinator_id INT DEFAULT NULL, admin_id INT DEFAULT NULL, student_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7877946 ON "user" (coordinator_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649642B8210 ON "user" (admin_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649CB944F1A ON "user" (student_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE admin ADD CONSTRAINT FK_880E0D76A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE coordinator ADD CONSTRAINT FK_15FE0E6AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE coordinator_school_class ADD CONSTRAINT FK_AE45A48CE7877946 FOREIGN KEY (coordinator_id) REFERENCES coordinator (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE coordinator_school_class ADD CONSTRAINT FK_AE45A48C14463F54 FOREIGN KEY (school_class_id) REFERENCES school_class (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE equipment ADD CONSTRAINT FK_D338D58354177093 FOREIGN KEY (room_id) REFERENCES room (id)');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF33EA000B10 FOREIGN KEY (class_id) REFERENCES school_class (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF33A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649E7877946 FOREIGN KEY (coordinator_id) REFERENCES coordinator (id)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649642B8210 FOREIGN KEY (admin_id) REFERENCES admin (id)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649CB944F1A FOREIGN KEY (student_id) REFERENCES student (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE admin DROP CONSTRAINT FK_880E0D76A76ED395');
        $this->addSql('ALTER TABLE coordinator DROP CONSTRAINT FK_15FE0E6AA76ED395');
        $this->addSql('ALTER TABLE coordinator_school_class DROP CONSTRAINT FK_AE45A48CE7877946');
        $this->addSql('ALTER TABLE coordinator_school_class DROP CONSTRAINT FK_AE45A48C14463F54');
        $this->addSql('ALTER TABLE equipment DROP CONSTRAINT FK_D338D58354177093');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF33EA000B10');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF33A76ED395');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649E7877946');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649642B8210');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649CB944F1A');
        $this->addSql('DROP TABLE admin');
        $this->addSql('DROP TABLE coordinator');
        $this->addSql('DROP TABLE coordinator_school_class');
        $this->addSql('DROP TABLE equipment');
        $this->addSql('DROP TABLE room');
        $this->addSql('DROP TABLE school_class');
        $this->addSql('DROP TABLE student');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
